services:
    weather:
        build: .
        image: microsoft
        container_name: weather
        tty: true
        working_dir: /root/explore
        
        ports:
            - 4010:4000       # HTTPs

        networks:
            web_network:
                ipv4_address: 192.168.20.3

        environment:
            - DOTNET_CLI_TELEMETRY_OPTOUT:true
            
        volumes:
            - ./WeatherApp:/root/explore

        command: dotnet run

networks:
    web_network:
        driver: bridge            
        ipam:
            config:
                - subnet: 192.168.20.0/24
